sudo: required

services:
  - docker

env:
  global:
    - TRAVIS_COMMIT_SHORT=${TRAVIS_COMMIT::8}

script:
  - true

deploy:
  provider: script
  script: make travis-build-docker
  on:
    branch: master
